update docker versions

diff --git a/php-8.0/Dockerfile b/php-8.0/Dockerfile
--- a/php-8.0/Dockerfile
+++ b/php-8.0/Dockerfile
@@ -1,22 +1,126 @@
 FROM php:8.0-fpm
 
-# Update image packages
-RUN apt-get update \
-    && apt-get install --no-install-recommends --assume-yes --quiet ca-certificates curl git \
-    && rm -rf /var/lib/apt/lists/
+# persistent dependencies
+RUN set -eux; \
+    apt-get update; \
+    apt-get install -y --no-install-recommends \
+    # Ghostscript is required for rendering PDF previews
+    ghostscript \
+    ; \
+    rm -rf /var/lib/apt/lists/*
+
+# install the PHP extensions we need (https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions)
+RUN set -ex; \
+    \
+    savedAptMark="$(apt-mark showmanual)"; \
+    \
+    apt-get update; \
+    apt-get install -y --no-install-recommends \
+    libfreetype6-dev \
+    libjpeg-dev \
+    libmagickwand-dev \
+    libpng-dev \
+    libzip-dev \
+    git \
+    ; \
+    \
+    docker-php-ext-configure gd --with-freetype --with-jpeg; \
+    docker-php-ext-install -j "$(nproc)" \
+    bcmath \
+    exif \
+    gd \
+    mysqli \
+    zip \
+    ; \
+    git clone https://github.com/Imagick/imagick; \
+    cd imagick; \
+    phpize && ./configure; \
+    make; \
+    make install; \
+    \
+    docker-php-ext-enable imagick; \
+    \
+    # reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
+    apt-mark auto '.*' > /dev/null; \
+    apt-mark manual $savedAptMark; \
+    ldd "$(php -r 'echo ini_get("extension_dir");')"/*.so \
+    | awk '/=>/ { print $3 }' \
+    | sort -u \
+    | xargs -r dpkg-query -S \
+    | cut -d: -f1 \
+    | sort -u \
+    | xargs -rt apt-mark manual; \
+    \
+    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
+    rm -rf /var/lib/apt/lists/*
+
+# set recommended PHP.ini settings
+# see https://secure.php.net/manual/en/opcache.installation.php
+RUN set -eux; \
+    docker-php-ext-enable opcache; \
+    { \
+    echo 'opcache.memory_consumption=128'; \
+    echo 'opcache.interned_strings_buffer=8'; \
+    echo 'opcache.max_accelerated_files=4000'; \
+    echo 'opcache.revalidate_freq=2'; \
+    echo 'opcache.fast_shutdown=1'; \
+    } > /usr/local/etc/php/conf.d/opcache-recommended.ini
+# https://wordpress.org/support/article/editing-wp-config-php/#configure-error-logging
+RUN { \
+    # https://www.php.net/manual/en/errorfunc.constants.php
+    # https://github.com/docker-library/wordpress/issues/420#issuecomment-517839670
+    echo 'error_reporting = E_ERROR | E_WARNING | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_RECOVERABLE_ERROR'; \
+    echo 'display_errors = Off'; \
+    echo 'display_startup_errors = Off'; \
+    echo 'log_errors = On'; \
+    echo 'error_log = /dev/stderr'; \
+    echo 'log_errors_max_len = 1024'; \
+    echo 'ignore_repeated_errors = On'; \
+    echo 'ignore_repeated_source = Off'; \
+    echo 'html_errors = Off'; \
+    } > /usr/local/etc/php/conf.d/error-logging.ini
+
+
+ENV WORDPRESS_VERSION 5.6
+ENV WORDPRESS_SHA1 db8b75bfc9de27490434b365c12fd805ca6784ce
+
+RUN set -ex; \
+    curl -o wordpress.tar.gz -fSL "https://wordpress.org/wordpress-${WORDPRESS_VERSION}.tar.gz"; \
+    echo "$WORDPRESS_SHA1 *wordpress.tar.gz" | sha1sum -c -; \
+    # upstream tarballs include ./wordpress/ so this gives us /usr/src/wordpress
+    tar -xzf wordpress.tar.gz -C /usr/src/; \
+    rm wordpress.tar.gz; \
+    chown -R www-data:www-data /usr/src/wordpress; \
+    # pre-create wp-content (and single-level children) for folks who want to bind-mount themes, etc so permissions are pre-created properly instead of root:root
+    # wp-content/cache: https://github.com/docker-library/wordpress/issues/534#issuecomment-705733507
+    mkdir wp-content; \
+    for dir in /usr/src/wordpress/wp-content/*/ cache; do \
+    dir="$(basename "${dir%/}")"; \
+    mkdir "wp-content/$dir"; \
+    done; \
+    chown -R www-data:www-data wp-content; \
+    chmod -R 777 wp-content
+
+VOLUME /var/www/html
+
+COPY docker-entrypoint.sh /usr/local/bin/
+
+#############################
+### ADD CUSTOM EXTENSIONS ###
+#############################
 
 # Install the xDebug PHP excension
-RUN pecl install xdebug \
-    && docker-php-ext-enable xdebug \
-    && docker-php-source delete \
-    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > "$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini" \
-    && echo "xdebug.mode=debug" >> "$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini" \
-    && echo "xdebug.start_with_request=yes" >> "$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini" \
-    && echo "xdebug.client_host=host.docker.internal" >> "$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini" \
-    && echo "xdebug.client_port=9000" >> "$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini" \
-    && echo "xdebug.remote_handler=dbgp" >> "$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini" \
-    && echo "xdebug.discover_client_host=0" >> "$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini" \
-    && echo "xdebug.idekey=PHPSTORM" >> "$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini"
+# RUN pecl install xdebug \
+#     && docker-php-ext-enable xdebug \
+#     && docker-php-source delete \
+#     && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > "$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini" \
+#     && echo "xdebug.mode=debug" >> "$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini" \
+#     && echo "xdebug.start_with_request=yes" >> "$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini" \
+#     && echo "xdebug.client_host=host.docker.internal" >> "$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini" \
+#     && echo "xdebug.client_port=9000" >> "$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini" \
+#     && echo "xdebug.remote_handler=dbgp" >> "$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini" \
+#     && echo "xdebug.discover_client_host=0" >> "$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini" \
+#     && echo "xdebug.idekey=PHPSTORM" >> "$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini"
 
 # Install the Symfony VarDumper component
 RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
@@ -25,19 +129,19 @@ RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local
     && echo "auto_prepend_file=/var/www/vendor/autoload.php" >> "$PHP_INI_DIR/php.ini-development"
 
 # Install BlackFire extension
-RUN version=$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;") \
-    && curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/linux/amd64/$version \
-    && mkdir -p /tmp/blackfire \
-    && tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp/blackfire \
-    && mv /tmp/blackfire/blackfire-*.so $(php -r "echo ini_get ('extension_dir');")/blackfire.so \
-    && echo "extension=blackfire.so" >> "$PHP_INI_DIR/conf.d/blackfire.ini" \
-    && echo "blackfire.agent_socket=tcp://blackfire:8707" >> "$PHP_INI_DIR/conf.d/blackfire.ini" \
-    && rm -rf /tmp/blackfire /tmp/blackfire-probe.tar.gz
+# RUN version=$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;") \
+#     && curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/linux/amd64/$version \
+#     && mkdir -p /tmp/blackfire \
+#     && tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp/blackfire \
+#     && mv /tmp/blackfire/blackfire-*.so $(php -r "echo ini_get ('extension_dir');")/blackfire.so \
+#     && echo "extension=blackfire.so" >> "$PHP_INI_DIR/conf.d/blackfire.ini" \
+#     && echo "blackfire.agent_socket=tcp://blackfire:8707" >> "$PHP_INI_DIR/conf.d/blackfire.ini" \
+#     && rm -rf /tmp/blackfire /tmp/blackfire-probe.tar.gz
 
 # Install WP CLI
-RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
-    && chmod +x wp-cli.phar \
-    && mv wp-cli.phar /usr/local/bin/wp
+# RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
+#     && chmod +x wp-cli.phar \
+#     && mv wp-cli.phar /usr/local/bin/wp
 
 # Cleanup
 RUN apt-get clean
@@ -49,5 +153,6 @@ RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
 # Manage EntryPoint file
 COPY entrypoint.sh /bin/php-entrypoint.sh
 RUN ["chmod", "+x", "/bin/php-entrypoint.sh"]
+RUN ["chmod", "+x", "/usr/local/bin/docker-entrypoint.sh"]
 ENTRYPOINT ["/bin/php-entrypoint.sh"]
 CMD ["php-fpm"]
